// Generated by CoffeeScript 1.6.1
(function() {
  var dict, spellcheck;

  dict = [
    {
      search: 'entrepreneur'
    }, {
      search: 'cloud',
      correct: 'Internet'
    }
  ];

  chrome.storage.sync.set({
    dictionary: dict
  }, function() {
    return console.log("Synced dictionary");
  });

  spellcheck = function(event) {
    var fuse, match, matches, target, term, words, _i, _j, _len, _len1;
    target = event.target;
    words = target.value.split(/\b/);
    fuse = new Fuse(words, {
      threshold: 0.3
    });
    for (_i = 0, _len = dict.length; _i < _len; _i++) {
      term = dict[_i];
      matches = fuse.search(term.search);
      for (_j = 0, _len1 = matches.length; _j < _len1; _j++) {
        match = matches[_j];
        words[match] = term.correct || term.search;
      }
    }
    return target.value = words.join('');
  };

  document.addEventListener('change', spellcheck);

  /*
  Eventually we'd like to bind to the input event, but as of right now that
  jumps the cursor to the end of the line every time. Maybe this helps:
  http://stackoverflow.com/questions/512528/set-cursor-position-in-html-textbox
  */


}).call(this);
