// Generated by CoffeeScript 1.6.1
(function() {
  var add, list, load, refresh, words;

  words = {};

  load = function(dict) {
    var word, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = dict.length; _i < _len; _i++) {
      word = dict[_i];
      _results.push(add(word));
    }
    return _results;
  };

  add = function(word) {
    if (words.hasOwnProperty(word.search)) {
      throw "'" + word.search + "' is already in the dictionary";
    }
    words[word.search] = {};
    if (word.correct != null) {
      words[word.search].correct = word.correct;
    }
    if (word.threshold != null) {
      return words[word.search].threshold = word.threshold;
    }
  };

  list = function() {
    var word, _results;
    _results = [];
    for (word in words) {
      _results.push(console.log('%s: %o', word, words[word]));
    }
    return _results;
  };

  refresh = function() {
    var tbody, word;
    tbody = document.getElementById('wordList');
    return tbody.innerHTML = ((function() {
      var _results;
      _results = [];
      for (word in words) {
        _results.push("<tr data-word=\"" + word + "\"><td><a href=\"\"><i class=\"icon-remove-sign\" /></a></td><td>" + word + "</td><td>" + (words[word].correct || word) + "</td></tr>");
      }
      return _results;
    })()).join('');
  };

  chrome.storage.sync.get('dictionary', function(res) {
    load(res.dictionary);
    add({
      search: 'viral',
      correct: 'untenable'
    });
    return refresh();
  });

}).call(this);
